### ISSUE TITLE
Trabajo extra, por un punto adicional.

### ISSUE THREAD

**Issue by jcontrolresearch** [jcontrolresearch/StructuredProgramming#9]
![image](https://user-images.githubusercontent.com/57429237/129077605-eb0d3b33-f760-47d2-a5dd-81bdfcaf8b38.png)

Entrega: 12/08/2021

**Problema: Escriba un algoritmo que lea n-calificaciones hasta que el usuario introduzca un -1 y obtener el promedio**

NOTA: El problema fue planteado y encontrado una solución en las notas de la clase:  [notas]( https://ulsaoaxaca-my.sharepoint.com/personal/000001612_ulsaoaxaca_edu_mx/_layouts/OneNote.aspx?id=%2Fpersonal%2F000001612_ulsaoaxaca_edu_mx%2FDocuments%2FProgrammingBasis&wd=target%28Clases.one%7C98EBEF50-C222-4443-8F95-BA9F3690862D%2F11%5C%2F08%5C%2F2021%7C07728D95-3A14-4484-8E1C-7CFA3F488466%2F%29 )

Encuentre una solución distinta según su criterio y escriba el diagrama de flujo y pseudocodigo correspondiente

_**El punto extra tiene un valor inicial de 1 directo a su parcial para el primero que lo entregue
0.8 para el segundo , 0.6 para el tercero y así sucesivamente**_

**Comment by TadeoJarquin** [comment]
![imagen](https://user-images.githubusercontent.com/88383344/129133476-0d0f339e-9868-4bb2-bdda-14a15fbb3108.png)

**Comment by WECosC** [comment]
![Prog  Algoritmo +1](https://user-images.githubusercontent.com/88383024/129146268-458bd01f-f2c9-4e67-be59-246aa8555251.jpeg)
![Program  Algoritmo +1 pseudo](https://user-images.githubusercontent.com/88383024/129146269-5f85b97e-f293-42f0-b69c-cf59be6703d0.jpeg)

**Comment by AquinoLu** [comment]
![Trabajo extra  Pseudocódigo](https://user-images.githubusercontent.com/88382912/129301417-6e170f4a-11c7-4db4-a3f6-fdeda72d0f93.jpg)
![Trabajo extra  Diagrama de flujo](https://user-images.githubusercontent.com/88382912/129301424-badd01e6-665d-4a09-8838-a8c7aeddbafd.png)

**Comment by Christianct23** [comment]
![Actividad punto extra](https://user-images.githubusercontent.com/88382940/129305119-9107fd7f-1dc7-4d60-9ad5-f177f7bab114.jpeg)
